web:
  build: .
  volumes:
    - .:/app
  ports:
    - 4000:4000
  links:
    - db
    - redis
  environment:
    DATABASE_HOST: db
    REDIS_HOST: redis

db:
  image: postgres
  ports:
    - 5432:5432

redis:
  image: redis
  ports:
    - 6379:6379
